import type { NextPage } from "next";
import Head from "next/head";
import fs from "fs";
import path from "path";
import matter from "gray-matter";

import styles from "../styles/Home.module.css";
import Link from "next/link";
import Post from "../components/Post/Post";

const Home: NextPage = ({ posts }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ViralShots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="header-content">
        <h1 className="site-title">Viralshots Daily</h1>
        <br />
        <p className="site-content">
          3 Min reads that are fun, insightful and easy to understand. This is
          Finshots as you know it.
        </p>
      </div>

      <div className="gap-y-8 flex flex-wrap justify-center">
        {posts?.map((post: any, index: any) => (
          <Post post={post} key={index} />
        ))}
      </div>
    </div>
  );
};

export async function getStaticProps() {
  // get files from the posts dir
  const files = fs.readdirSync(path.join("posts"));

  // get slug and frontmatter from posts
  const posts = files.map((filename) => {
    // create slug
    const slug = filename.replace(".md", "");

    // get formatter
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );

    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
}

export default Home;
